<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\1_Utils\Utils.csproj" />
    <ProjectReference Include="..\5_RocketLeague\RocketLeague.csproj" />
    <ProjectReference Include="..\4_Network\Network.csproj" />
    <ProjectReference Include="..\6_RlTracker.Settings\RlTracker.Settings.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
